1주차/todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path
import myapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', myapp.views.home, name="home"),
    path('todoform/', myapp.views.todo_form, name="todo_form"),
    path('delete/<int:pk>', myapp.views.delete_todo, name="delete_todo"),
    path('edit/<int:pk>', myapp.views.edit_todo, name="edit_todo"),
    path('editpost/<int:pk>', myapp.views.edit_post, name="edit_post"),
    path('complete/<int:pk>', myapp.views.complete_todo, name="complete_todo"),

    path('calendar/', myapp.views.calendar, name="calendar"),
    path('calendar/get', myapp.views.calendar_get, name="calendar_get"),
    path('calendar/delete/<int:pk>', myapp.views.calendar_delete, name="calendar_delete"),
    path('calendar/complete/<int:pk>', myapp.views.calendar_complete, name="calendar_complete"),
    path('calendar/edit/<int:pk>', myapp.views.calendar_edit),
    path('calendar/edit/post/<int:pk>', myapp.views.calendar_edit_post, name="calendar_edit")
]

1주차/todolist/myapp/models.py
from email.policy import default
from django.db import models

class CurrDate(models.Model):
  id = models.AutoField(primary_key=True)
  year = models.IntegerField()
  month = models.IntegerField()
  date = models.IntegerField()
  cnt = models.IntegerField(default=0)

# Create your models here.
class Todo(models.Model):
  id = models.AutoField(primary_key=True)
  contents = models.CharField(max_length=300)
  complete = models.BooleanField(default=False)
  edit = models.BooleanField(default=False)
  date = models.DateTimeField(auto_now_add=True)
  day = models.ForeignKey(CurrDate, null=True, blank=True, on_delete=models.CASCADE)

  def __str__(self):
    return self.contents

1주차/todolist/myapp/forms.py
from dataclasses import field
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
  class Meta:
    model = Todo
    fields = ['contents']

1주차/todolist/myapp/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from .models import Todo
from .forms import TodoForm
from .models import CurrDate

# Create your views here.
def home(request):
  form = TodoForm()
  todos = Todo.objects.filter().order_by('date')
  dates = CurrDate.objects.all()

  return render(request, 'index.html', 
    {'todos': todos, 'form': form, 'dates': dates})


def todo_form(request):
  # POST 요청 -> 작성한 폼 가져와서 DB 에 저장하고 'home'으로 이동
  if request.method == 'POST' or request.method == 'FILES':
    form = TodoForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect('home')

  # GET 요청이면 home으로
  return redirect('home')

  # return render(request, 'todo_form.html', {'form': form})


def delete_todo(req, pk):
  todo = get_object_or_404(Todo, id=pk)
  todo.delete()
  return redirect('home')


def edit_todo(req, pk):
  todo = get_object_or_404(Todo, id=pk)

  if todo.edit == False:
    todo.edit = True
  else:
    todo.edit = False

  todo.save()
  return redirect('home')

def edit_post(req, pk):
  todo = get_object_or_404(Todo, id=pk)

  if req.method == 'POST':
    todo.contents = req.POST['edit_contents']
    todo.edit = False
    todo.save()

  return redirect('home')


def complete_todo(req, pk):
  print('current path: ',req.path)
  todo = get_object_or_404(Todo, id=pk)
  y = todo.day.year
  m = todo.day.month
  d = todo.day.date
  print(y, m, d)

  if todo.complete == False:
    todo.complete = True
  else:
    todo.complete = False

  todo.save()
  
  form = TodoForm()
  
  # return redirect('home')
  return redirect('calender')



def calendar(req):
  form = TodoForm()

  return render(req, 'calendar.html')
  
def getDate(req):
  year = req.GET.get('year', None)
  month = req.GET.get('month', None)
  date = req.GET.get('date', None)

  return year, month, date

def calendar_get(req):
  form = TodoForm()

  # year = req.GET.get('year', None)
  # month = req.GET.get('month', None)
  # date = req.GET.get('date', None)

  year, month, date = getDate(req)
  print('test getDate: ', year, month, date)
  flag = True

  try:
      currDate = CurrDate.objects.get(year=year, month=month, date=date)
  except CurrDate.DoesNotExist: # if not, send DoesNotExist
      # raise Http404("Question does not exist") #what specific message to show
      print("404 error")
      flag = False
      currDate = CurrDate()
      currDate.year = year
      currDate.month = month
      currDate.date = date
      currDate.save()

  print('currDate: ', currDate)

  if req.method == 'POST' or req.method == 'FILES':
    print(year, month, date)
    filled = TodoForm(req.POST, req.FILES)
    if filled.is_valid():
      unfinished = filled.save(commit=False)
      unfinished.day = currDate
      unfinished.save()
      currDate.cnt = currDate.cnt + 1
      currDate.save()
  
  return render(req, 'calendar.html', {
    'year': year, 'month': month, 'date': date,
    'flag': flag, 'form': form, 'currDate': currDate
  })


def calendar_delete(req, pk):

  year, month, date = getDate(req)

  todo = get_object_or_404(Todo, id=pk)
  currDate = todo.day
  todo.delete()

  form = TodoForm()
  currDate.cnt = currDate.cnt - 1
  currDate.save()

  return render(req, 'calendar.html', {
    'year': year, 'month': month, 'date': date,
    'form': form, 'currDate': currDate
  })


def calendar_complete(req, pk):
  year, month, date = getDate(req)

  todo = get_object_or_404(Todo, id=pk)
  currDate = todo.day

  if todo.complete == False:
    todo.complete = True
  else:
    todo.complete = False

  todo.save()
  
  form = TodoForm()
  
  return render(req, 'calendar.html', {
    'year': year, 'month': month, 'date': date,
    'form': form, 'currDate': currDate
  })

def calendar_edit(req, pk):
  year, month, date = getDate(req)
  todo = get_object_or_404(Todo, id=pk)
  currDate = todo.day
  form = TodoForm()

  if todo.edit == False:
    todo.edit = True
  else:
    todo.edit = False

  todo.save()
  return render(req, 'calendar.html', {
    'year': year, 'month': month, 'date': date,
    'form': form, 'currDate': currDate
  })


def calendar_edit_post(req, pk):
  year, month, date = getDate(req)
  todo = get_object_or_404(Todo, id=pk)
  currDate = todo.day
  form = TodoForm()

  if req.method == 'POST':
    todo.contents = req.POST['edit_contents']
    todo.edit = False
    todo.save()

  return render(req, 'calendar.html', {
    'year': year, 'month': month, 'date': date,
    'form': form, 'currDate': currDate
  })

1주차/todolist/myapp/templates/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

  <!-- <script defer src="{% static 'js/main.js' %}"></script> -->
  <script defer src="{% static 'js/calendar.js' %}"></script>

  <title>Document</title>
</head>

<body>

  <div class="info-box">

    <div class="day-clock-div" onclick="location.href='/'"
      style="cursor: pointer;"
    >
      <span class="material-icons">
        home
      </span>
    </div>

    <p class="todo-text">
      {{ year }}년 {{ month }}월 {{ date }}일의 To-do list
    </p>

    <form class="todo-form">
      {% csrf_token %}
      <div class="input-div">
        <input type="text" name="contents" id="contents" maxlength="30">
        <input type="submit" value="작성" id="submit-btn">
      </div>
    </form>

  </div>

  <div class="contents-box">
    <div class="todo-list">
      {% for todo in currDate.todo_set.all %}

      <div class="todo-box">

        <div class="todo">

          {% if todo.edit %}
          <form id="{{ todo.id }}" action="{% url 'calendar_edit' todo.id %}?year={{year}}&month={{month}}&date={{date}}" method="POST" class="edit-div">
            {% csrf_token %}
            <input class="edit-input" type="text" value="{{ todo.contents }}" name="edit_contents" id="edit_contents"
              maxlength="30" />
            <input id="{{ todo.id }}" class="edit-submit" type="submit" value="수정">
          </form>
          {% else %}
          <div class="text">{{ todo.contents }}</div>
          {% endif %}

          {% if todo.complete %}
          <div class="complete">완료</div>
          {% endif %}
          <div class="write-date">{{ todo.date }}</div>
        </div>

        <div class="icons">
          <span id="{{ todo.id }}" class="material-icons check">
            check_circle
          </span>
          <span id="{{ todo.id }}" class="material-icons cancel">
            cancel
          </span>
          <span id="{{ todo.id }}" class="material-icons edit" >
            edit
          </span>
        </div>
      </div>

      {% endfor %}
    </div>


  </div>

</body>

</html>

1주차/todolist/myapp/templates/date.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div>{{ year }}</div>
  <div>{{ month }}</div>
  <div>{{ date }}</div>
</body>
</html>

1주차/todolist/myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

  <script defer src="{% static 'js/main.js' %}"></script>
  <!-- <script defer src="{% static 'js/calendar.js' %}"></script> -->

  <title>Document</title>
</head>

<body>

  <div class="info-box">

    {% for date in dates %}
      {% if date.cnt > 0 %}
      <div class="active">{{date.year}} {{date.month}} {{date.date}}</div>
      {% endif %}
    {% endfor %}

    <div class="day-clock-div">
      <div class="date">2022년 1월 1일</div>
      <div class="clock">00시 00분 00초</div>
    </div>

    <p class="todo-text">To-do list Calendar</p>

  </div>

  <div class="contents-box">

    <div class="calendar">

      <div class="calendar-nav">
        <span class="material-icons arrow_left">
          arrow_left
        </span>
        <span class="year-month">
          2022년 1월
        </span>
        <span class="material-icons arrow_right">
          arrow_right
        </span>
      </div>

      <div class="day-nav">
        <p class="day sunday">일</p>
        <p class="day">월</p>
        <p class="day">화</p>
        <p class="day">수</p>
        <p class="day">목</p>
        <p class="day">금</p>
        <p class="day saturday">토</p>
      </div>
      <div class="date-div">
        <div class="calendar-date day sunday"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day saturday"></div>
        <div class="calendar-date day sunday"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day saturday"></div>
        <div class="calendar-date day sunday"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day saturday"></div>
        <div class="calendar-date day sunday"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day saturday"></div>
        <div class="calendar-date day sunday"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day saturday"></div>
        <div class="calendar-date day sunday"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day"></div>
        <div class="calendar-date day saturday"></div>
      </div>

    </div>
  </div>


</body>

</html>